Repository ISIS3510-202410-Team36/Flutter, pull requests merged in 2024-05, with the labels that each got.

#5 2 search view enhancement
  unimarket/assets/images/logo.png
  unimarket/assets/images/no_internet_connection.png
  unimarket/assets/images/no_search_results.png
  unimarket/assets/images/search_something.png
  unimarket/assets/images/user_profile_icon.png
  unimarket/lib/Controllers/search_controllerUnimarket.dart
  unimarket/lib/Models/Repository/productReposirory.dart
  unimarket/lib/Models/model.dart
  unimarket/lib/Models/product_model.dart
  unimarket/lib/Models/seller_model.dart
  unimarket/lib/Views/body_view.dart
  unimarket/lib/Views/login_view.dart
  unimarket/lib/Views/productDetail_view.dart
  unimarket/lib/Views/publish_view.dart
  unimarket/lib/Views/register_view.dart
  unimarket/lib/Views/search_view.dart
  unimarket/lib/main.dart
  unimarket/lib/resources/shimmer_effect.dart
  unimarket/pubspec.lock
  unimarket/pubspec.yaml
Labels: enhancement, Sprint 3

#7 commit final
  unimarket/lib/Views/search_view/search_view.dart
Labels: Sprint 4

#8 Enhancement finished
  unimarket/lib/main.dart
Labels: enhancement, Sprint 3

#10 32 concurrency strategy
  unimarket/lib/Views/login_view.dart
  unimarket/pubspec.lock
  unimarket/pubspec.yaml
Labels: Sprint 4, concurrency

#11 9 micro optimizations lifecycle of widgets
  unimarket/lib/Views/publish_view/publish_view.dart
  unimarket/lib/main.dart
Labels: Sprint 4

#13 unused imports, dead code, commented code, and bad prints removed
  unimarket/lib/Controllers/auth_controller.dart
  unimarket/lib/Controllers/cart_controller.dart
  unimarket/lib/Controllers/home_controller.dart
  unimarket/lib/Controllers/network_controller.dart
  unimarket/lib/Controllers/productDetail_controller.dart
  unimarket/lib/Controllers/publish_controller.dart
  unimarket/lib/Models/Repository/cartRepository.dart
  unimarket/lib/Models/product_model.dart
  unimarket/lib/Models/seller_model.dart
  unimarket/lib/Views/body_view.dart
  unimarket/lib/Views/cart_view.dart
  unimarket/lib/Views/chat_view.dart
  unimarket/lib/Views/home_view.dart
  unimarket/lib/Views/login_view.dart
  unimarket/lib/Views/register_view.dart
  unimarket/lib/main.dart
  unimarket/lib/theme.dart
Labels: enhancement, Sprint 4, micro-optimization
